import Head from "next/head";
import Login from "./login";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog-Post-App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Login />
      </main>
    </div>
  );
}
